name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

  test:
    needs: setup
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up SQLite database
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec
