name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        exec $SHELL
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
        exec $SHELL
        git clone https://github.com/rbenv/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
        rbenv install 3.0.2
        rbenv global 3.0.2

    - name: Install rails
      run: gem install rails

    - name: Install dependencies
      run: |
        bundle config set --local without 'development:test'
        bundle install --jobs 4 --retry 3

    - name: Set up SQLite database
      run: |
        cp config/database.ci.yml config/database.yml
        bundle exec rails db:migrate

    - name: Run tests
      run: bundle exec rspec
